export { Homepage } from "./homepage/Homepage";
export { PageNotFound } from "./pageNotFound/PageNotFound";
export { RulesPage } from "./rulespage/RulesPage";
export { QuizListingPage } from "./quizListingPage/QuizListingPage";
export { RequiresAuth } from "./requiresAuth/RequiresAuth";
export { LoginPage } from "./loginpage/LoginPage";
export { SignupPage } from "./signuppage/SignupPage";
export { SingleQuizPage } from "./singleQuizPage/SingleQuizPage";
export { ResultPage } from "./resultpage/ResultPage";
